GET http://localhost:3000/movies/
##

POST http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###

GET http://localhost:3000/movies/50/
###

PUT http://localhost:3000/movies/53
Content-Type: application/json

{
  "directorId": 24,
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###


DELETE http://localhost:3000/movies/15
###

GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/23/movies/
###


# //movie table
# GET http://localhost:3000/movies
# ###

# //director table
# GET http://localhost:3000/directors
# ###